### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by itsdrew** [micronaut-guides/micronaut-oauth2-okta#2]
I tried following along with the tutorial and got this error:

DefaultStateProvider is not abstract and does not override abstract method deserializeState(String) in StateProvider

I tried pulling this repo and got the same exact error.

**Comment by ilopmar** [comment]
Same error while upgrading the guide to `1.1.0.BUILD-SNAPSHOT`

https://travis-ci.org/micronaut-guides/micronaut-oauth2-okta/builds/518659594#L646

**Comment by quangthe** [comment]
According to https://github.com/micronaut-projects/micronaut-oauth2, the micronaut-oauth2 project has been merged into micronaut-security project (https://github.com/micronaut-projects/micronaut-security). But the document doesn't have any guide for oauth2 (https://micronaut-projects.github.io/micronaut-security/1.1.x/guide/)

**Comment by akyong** [comment]
> According to https://github.com/micronaut-projects/micronaut-oauth2, the micronaut-oauth2 project has been merged into micronaut-security project (https://github.com/micronaut-projects/micronaut-security). But the document doesn't have any guide for oauth2 (https://micronaut-projects.github.io/micronaut-security/1.1.x/guide/)

ough! The document does not match anymore.
https://guides.micronaut.io/micronaut-oauth2-okta/guide/index.html

I think this document should be change.

**Comment by sdelamo** [comment]
I’ve updated the guide. OpenID connect has been changed/improved heavily in the past weeks. Apologies for the confusion.
